import { events, places, defaultChecklist, dateLabels, transportGuides, officialLinks } from './data.js';
import { eventsForDate, toggleChecklist, toggleEvent, addCustomEvent, deleteCustomEvent, categoryFilter, createBackup, restoreBackup, createICS, googleMapsUrl, downloadText, departureReminderDecision } from './planner.js';
import { addAttachment, listAttachments, getAttachment, deleteAttachment } from './storage.js';
import { safeTooltipContent } from './security.js';
import { applyTimelineMotion, dateTransitionDirection, prefersReducedMotion, revealElements, updateTabIndicator } from './motion.js';

const KEY='fukuoka-planner-state-v1';
const REMINDER_KEY='fukuoka-planner-reminder-date';
let state=loadState(); let selectedDate='2026-08-28'; let map; let markers=[]; let routeLayer; let nominatimRequest=null; let routeRequest=null; let lastNominatimStarted=0;
function freshState(){return {version:1,checklist:structuredClone(defaultChecklist),customEvents:[],completedEvents:[]};}
function mergeChecklistDefaults(clean){const byId=new Map(clean.checklist.map(item=>[item.id,item]));return {...clean,checklist:defaultChecklist.map(item=>({...structuredClone(item),done:byId.get(item.id)?.done??item.done}))};}
function loadState(){try{const raw=localStorage.getItem(KEY);if(!raw)return freshState();return mergeChecklistDefaults(restoreBackup(raw));}catch{try{localStorage.removeItem(KEY);}catch{}return freshState();}}
function persist(nextState){try{localStorage.setItem(KEY,JSON.stringify(nextState));state=nextState;return true;}catch{toast('저장 공간이 부족하거나 차단되어 변경을 저장하지 못했어요.');return false;}}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(message){const el=document.querySelector('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200);}

function renderDates(){document.querySelector('#date-chips').innerHTML=Object.entries(dateLabels).map(([date,label])=>`<button data-date="${date}" class="${date===selectedDate?'active':''}">${label}</button>`).join('');}
function renderTimeline(direction='still'){const all=[...events,...state.customEvents];const done=new Set(state.completedEvents);const list=eventsForDate(all,selectedDate);const timeline=document.querySelector('#timeline');timeline.innerHTML=list.map(e=>`<article class="event ${e.fixed?'fixed':''} ${done.has(e.id)?'done':''}"><button class="icon-btn" data-complete="${esc(e.id)}" aria-label="${done.has(e.id)?'완료 취소':'완료 표시'}">${done.has(e.id)?'✓':'○'}</button><span class="event-time">${esc(e.start)}${e.end?` — ${esc(e.end)}`:''}</span>${e.fixed?'<span class="tag">고정</span>':''}<h3>${esc(e.title)}</h3><p>📍 ${esc(e.location||'장소 미정')}</p>${e.notes?`<p>${esc(e.notes)}</p>`:''}${e.custom?`<div class="event-actions"><button class="icon-btn" data-delete="${esc(e.id)}" aria-label="일정 삭제">×</button></div>`:''}</article>`).join('')||'<p class="status">등록된 일정이 없어요.</p>';applyTimelineMotion(timeline,direction,prefersReducedMotion());}
function renderSchedule(direction='still'){renderDates();renderTimeline(direction);}
function renderChecklist(){const done=state.checklist.filter(x=>x.done).length;const percent=Math.round(done/state.checklist.length*100)||0;document.querySelector('#check-progress').textContent=`${percent}%`;document.querySelector('#progress-bar').style.width=`${percent}%`;document.querySelector('#check-list').innerHTML=state.checklist.map(x=>`<label class="check-item"><input data-check="${esc(x.id)}" type="checkbox" ${x.done?'checked':''}><span>${esc(x.label)}</span><small>${esc(x.category)}</small></label>`).join('');}
function renderFood(){document.querySelector('#food-list').innerHTML=places.filter(p=>p.category==='food'&&p.id!=='unafuji').map(p=>`<article class="food-card"><div><h3>${esc(p.name)}</h3><p>${esc(p.caption)}</p><p class="food-tip"><b>팁</b> ${esc(p.tip)}</p><div class="card-links"><a href="${googleMapsUrl(p)}" target="_blank" rel="noopener">Google Maps</a>${p.officialUrl?`<a href="${esc(p.officialUrl)}" target="_blank" rel="noopener">공식 사이트</a>`:''}</div></div></article>`).join('');}
function renderTransport(){document.querySelector('#transport-guides').innerHTML=transportGuides.map(g=>`<article class="transport-card"><h3>${esc(g.title)}</h3><p><b>1순위</b> ${esc(g.primary)}</p><p><b>대안</b> ${esc(g.fallback)}</p><a class="important-link" href="${esc(g.mapsUrl)}" target="_blank" rel="noopener">Google Maps 대중교통 ↗</a></article>`).join('');document.querySelector('#official-links').innerHTML=officialLinks.map(link=>`<a class="important-link" href="${esc(link.url)}" target="_blank" rel="noopener">${esc(link.title)} ↗</a>`).join('');}

const tabs=document.querySelector('.tabs');
function showTab(id){const activeButton=tabs.querySelector(`[data-tab="${id}"]`);tabs.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b===activeButton);b.toggleAttribute('aria-current',b===activeButton)});document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));updateTabIndicator(tabs,activeButton);if(id==='map')setTimeout(initMap,0);if(id==='vault')renderAttachments();}
tabs.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)showTab(b.dataset.tab)});
document.querySelector('#date-chips').addEventListener('click',e=>{const b=e.target.closest('[data-date]');if(b){const direction=dateTransitionDirection(selectedDate,b.dataset.date);selectedDate=b.dataset.date;renderSchedule(direction);}});
document.querySelector('#timeline').addEventListener('click',e=>{const complete=e.target.closest('[data-complete]');if(complete&&persist(toggleEvent(state,complete.dataset.complete)))renderTimeline();const del=e.target.closest('[data-delete]');if(del&&confirm('이 일정을 삭제할까요?')&&persist(deleteCustomEvent(state,del.dataset.delete))){renderTimeline();toast('일정을 삭제했어요.');}});
document.querySelector('#check-list').addEventListener('change',e=>{if(e.target.dataset.check){if(persist(toggleChecklist(state,e.target.dataset.check)))renderChecklist();else renderChecklist();}});

const dialog=document.querySelector('#event-dialog');document.querySelector('#add-open').onclick=()=>dialog.showModal();document.querySelector('#dialog-close').onclick=()=>dialog.close();document.querySelector('#event-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{const next=addCustomEvent(state,data);if(!persist(next))return;selectedDate=data.date;renderSchedule();e.currentTarget.reset();dialog.close();toast('새 일정을 추가했어요.');}catch(error){document.querySelector('#form-error').textContent=error.message;}};

function initMap(){if(map){map.invalidateSize();return;}if(!window.L){document.querySelector('#map-status').textContent='지도 라이브러리를 불러오지 못했어요. 일정과 Google Maps 링크는 계속 사용할 수 있습니다.';return;}map=L.map('leaflet-map',{zoomControl:true}).setView([33.606,130.42],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);renderMarkers('all');}
function hasCoordinates(p){return Number.isFinite(p.lat)&&Number.isFinite(p.lng);}
function renderMarkers(category){if(!map)return;markers.forEach(m=>m.remove());markers=categoryFilter(places,category).filter(hasCoordinates).map(p=>L.marker([p.lat,p.lng]).addTo(map).bindTooltip(safeTooltipContent(document,p.name)).on('click',()=>selectPlace(p)));}
function selectPlace(p){document.querySelector('#place-card').innerHTML=`<h3>${esc(p.name)}</h3><p>${esc(p.caption||'검색한 장소')}</p><a class="important-link" href="${googleMapsUrl(p)}" target="_blank" rel="noopener">Google Maps에서 보기 ↗</a>`;if(hasCoordinates(p))map?.panTo([p.lat,p.lng]);}
document.querySelector('#map-filters').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;document.querySelectorAll('#map-filters button').forEach(x=>x.classList.toggle('active',x===b));renderMarkers(b.dataset.category);};
const NOMINATIM_ATTRIBUTION='검색 데이터: © OpenStreetMap contributors · Nominatim';
const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
document.querySelector('#search-form').onsubmit=async e=>{
  e.preventDefault();
  if(nominatimRequest)return;
  const query=document.querySelector('#place-search').value.trim();if(!query||!map)return;
  const form=e.currentTarget;const submit=form.querySelector('button[type="submit"],button');const status=document.querySelector('#map-status');
  nominatimRequest=new AbortController();submit.disabled=true;status.textContent=`장소를 찾고 있어요… · ${NOMINATIM_ATTRIBUTION}`;
  let timeout;
  try{
    await wait(Math.max(0,1000-(Date.now()-lastNominatimStarted)));
    lastNominatimStarted=Date.now();timeout=setTimeout(()=>nominatimRequest?.abort(),10000);
    const url=new URL('https://nominatim.openstreetmap.org/search');url.search=new URLSearchParams({q:`${query}, Fukuoka, Japan`,format:'jsonv2',limit:'5',countrycodes:'jp','accept-language':'ko'});
    const response=await fetch(url,{headers:{Accept:'application/json'},signal:nominatimRequest.signal});if(!response.ok)throw new Error('search failed');
    const results=await response.json();if(!Array.isArray(results)||!results.length){status.textContent=`검색 결과가 없어요. 일본어 이름이나 더 짧은 검색어를 시도해 주세요. · ${NOMINATIM_ATTRIBUTION}`;return;}
    const r=results[0];const displayName=String(r.display_name??'검색한 장소');const p={name:displayName.split(',')[0],caption:displayName,lat:Number(r.lat),lng:Number(r.lon)};if(!hasCoordinates(p))throw new Error('invalid coordinates');
    L.marker([p.lat,p.lng]).addTo(map).bindTooltip(safeTooltipContent(document,p.name)).openTooltip();map.setView([p.lat,p.lng],15);selectPlace(p);status.textContent=`${results.length}개의 검색 결과를 찾았어요. 첫 번째 장소를 표시합니다. · ${NOMINATIM_ATTRIBUTION}`;
  }catch{status.textContent=`장소 검색 서비스에 연결할 수 없어요. 아래 Google Maps 링크를 이용해 주세요. · ${NOMINATIM_ATTRIBUTION}`;}
  finally{clearTimeout(timeout);nominatimRequest=null;submit.disabled=false;}
};
document.querySelector('.route-actions').onclick=async e=>{
  const button=e.target.closest('[data-route]');if(!button||!map||routeRequest)return;
  const [a,b]=button.dataset.route.split(',').map(id=>places.find(p=>p.id===id));const status=document.querySelector('#map-status');if(!hasCoordinates(a)||!hasCoordinates(b)){status.textContent='좌표가 없는 장소는 Google Maps 검색 링크를 이용해 주세요.';return;}
  routeRequest=new AbortController();button.disabled=true;status.textContent='자동차 경로를 계산하고 있어요…';const timeout=setTimeout(()=>routeRequest?.abort(),12000);
  try{const response=await fetch(`https://router.project-osrm.org/route/v1/driving/${a.lng},${a.lat};${b.lng},${b.lat}?overview=full&geometries=geojson`,{signal:routeRequest.signal});if(!response.ok)throw new Error();const json=await response.json();if(json.code!=='Ok'||!json.routes?.[0])throw new Error();routeLayer?.remove();routeLayer=L.geoJSON(json.routes[0].geometry,{style:{color:'#ef695c',weight:5}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[30,30]});status.textContent=`예상 ${(json.routes[0].duration/60).toFixed(0)}분 · ${(json.routes[0].distance/1000).toFixed(1)}km (자동차·실시간 교통 미반영)`;}catch{status.textContent='자동차 경로 서비스에 연결할 수 없어요. Google Maps 길찾기를 이용해 주세요.';selectPlace(b);}finally{clearTimeout(timeout);routeRequest=null;button.disabled=false;}
};

document.querySelector('#ics').onclick=()=>{downloadText('fukuoka-trip-2026.ics',createICS([...events,...state.customEvents]),'text/calendar;charset=utf-8');toast('캘린더 파일을 만들었어요.');};document.querySelector('#backup').onclick=()=>{downloadText('fukuoka-planner-backup.json',createBackup(state),'application/json');toast('백업을 저장했어요.');};document.querySelector('#restore').onchange=async e=>{try{if(!e.target.files[0])return;const next=mergeChecklistDefaults(restoreBackup(await e.target.files[0].text()));if(!persist(next))return;renderSchedule();renderChecklist();toast('백업을 복원했어요.');}catch(error){toast(`복원 실패: ${error.message}`);}finally{e.target.value='';}};
function maybeDepartureReminder(){if(!('Notification'in window)||Notification.permission!=='granted')return;try{const decision=departureReminderDecision({departure:'2026-08-28',permission:Notification.permission,lastNotifiedDate:localStorage.getItem(REMINDER_KEY)});if(decision.notify){new Notification(decision.daysUntil===0?'오늘 후쿠오카로 출발해요!':`후쿠오카 출발 D-${decision.daysUntil}`,{body:'체크리스트와 최신 교통 시간표를 확인해 주세요.',icon:'icons/icon.svg'});localStorage.setItem(REMINDER_KEY,decision.localDate);}}catch{toast('출발 알림을 표시하거나 기록하지 못했어요.');}}
document.querySelector('#notify').onclick=async()=>{try{if(!('Notification'in window)){toast('이 브라우저는 알림을 지원하지 않아요.');return;}const result=await Notification.requestPermission();if(result==='granted'){toast('출발 7일 전부터 앱을 열 때 하루 한 번 알림을 확인해요.');maybeDepartureReminder();}else toast('알림 권한이 허용되지 않았어요.');}catch{toast('알림 권한을 요청하지 못했어요.');}};
async function renderAttachments(){const box=document.querySelector('#attachment-list');try{const list=await listAttachments();box.innerHTML=list.length?list.map(x=>`<div class="attachment-row"><span>📎</span><div><b>${esc(x.name)}</b><br><small>${(x.size/1024).toFixed(1)} KB · ${new Date(x.createdAt).toLocaleDateString('ko')}</small></div><button data-download="${esc(x.id)}" aria-label="${esc(x.name)} 다운로드">↓</button><button data-remove="${esc(x.id)}" aria-label="${esc(x.name)} 삭제">×</button></div>`).join(''):'<p>아직 저장한 파일이 없어요.</p>';}catch{box.innerHTML='<p class="error">이 브라우저에서 기기 저장소를 열 수 없어요.</p>';}}
document.querySelector('#attachment-input').onchange=async e=>{try{if(e.target.files[0])await addAttachment(e.target.files[0]);await renderAttachments();toast('파일을 기기에 저장했어요.');}catch(error){toast(error.message||'파일을 저장하지 못했어요.');}finally{e.target.value='';}};document.querySelector('#attachment-list').onclick=async e=>{const down=e.target.closest('[data-download]');const remove=e.target.closest('[data-remove]');try{if(down){const record=await getAttachment(down.dataset.download);if(!record)throw new Error('파일을 찾을 수 없어요.');const a=document.createElement('a');a.href=URL.createObjectURL(record.blob);a.download=record.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}if(remove&&confirm('이 파일을 삭제할까요?')){await deleteAttachment(remove.dataset.remove);await renderAttachments();toast('파일을 삭제했어요.');}}catch(error){toast(error.message||'파일 작업을 완료하지 못했어요.');}};
function networkStatus(){const pill=document.querySelector('#online-pill');pill.textContent=navigator.onLine?'온라인':'오프라인';pill.classList.toggle('offline',!navigator.onLine);}addEventListener('online',networkStatus);addEventListener('offline',networkStatus);networkStatus();
function renderDDay(){const today=new Date();today.setHours(0,0,0,0);const departure=new Date(2026,7,28);const days=Math.ceil((departure-today)/86400000);document.querySelector('#d-day').textContent=days>0?`D-${days}`:days===0?'D-DAY':days>=-2?'여행 중':'다녀온 여행';}renderDDay();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>toast('오프라인 기능을 준비하지 못했지만 앱은 계속 사용할 수 있어요.')));
renderSchedule();renderChecklist();renderFood();renderTransport();maybeDepartureReminder();
if(!prefersReducedMotion())document.body.classList.add('motion-ready');
requestAnimationFrame(()=>{updateTabIndicator(tabs,tabs.querySelector('.active'));revealElements();});
addEventListener('resize',()=>updateTabIndicator(tabs,tabs.querySelector('.active')),{passive:true});
