// 첨부 인포그래픽의 음식 종류를 텐진역·다이묘·이마이즈미 인근 지점으로 다시 정리한 11곳입니다.
// 하카타역 지점은 제외했습니다. 가격 확인일: 2026-08-26. 공식 가격을 확인하지 못한 항목은 추정하지 않습니다.
export const restaurantGuide=[
  {number:1,id:'shinshin-tenjin',name:'博多純情らーめん ShinShin 天神本店',koreanName:'하카타 신신 라멘 텐진 본점',category:'라멘',area:'텐진',menus:[{name:'하카타 신신 라멘',price:'870엔',priceNote:'세금 포함'},{name:'반숙계란 라멘',price:'1,030엔',priceNote:'세금 포함'}],address:'〒810-0001 福岡県福岡市中央区天神3-2-19 1F',lat:33.592673,lng:130.396814,mapQuery:'博多純情らーめん ShinShin 天神本店',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 6분',officialUrl:'https://www.hakata-shinshin.com/tenpo_tenjin',menuUrl:'https://www.hakata-shinshin.com/menu_tenjin01',evidenceNote:'지점·가격: ShinShin 공식 사이트 · 사진 출처 링크 제공',image:'assets/restaurants/01-shinshin-tenjin.webp',imageAlt:'ShinShin 텐진 본점의 하카타 라멘',imageSource:'https://www.hakata-shinshin.com/tenpo_tenjin'},
  {number:2,id:'unafuji-daimyo',name:'炭焼 うな富士 福岡大名別邸',koreanName:'숯불 우나후지 후쿠오카 다이묘 별저',category:'장어',area:'다이묘',menus:[{name:'상 히츠마부시',price:'5,640엔',priceNote:'지점 공식 일본어 메뉴 PDF · 세금 포함'}],address:'〒810-0041 福岡県福岡市中央区大名2-1-41',lat:33.588668,lng:130.3948393,mapQuery:'炭焼 うな富士 福岡大名別邸',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 3분',officialUrl:'https://sumiyaki-unafuji.com/shops/fukuoka_daimyo/',menuUrl:'https://sumiyaki-unafuji.com/wp-content/uploads/2025/12/menu_jp-13.pdf',image:'assets/restaurants/02-unafuji-daimyo.webp',imageAlt:'우나후지 공식 메뉴의 히츠마부시',imageSource:'https://sumiyaki-unafuji.com/menu/',evidenceNote:'매장·가격·사진: 우나후지 공식 사이트와 지점 공식 메뉴 PDF · 토 11:00 예약 확정'},
  {number:3,id:'kanetora-tenjin-nishidori',name:'麺や兼虎 天神西通り店',koreanName:'멘야 카네토라 텐진 니시도리점',category:'츠케멘',area:'다이묘',menus:[{name:'농후 츠케멘',price:'1,300엔',priceNote:'공식 메뉴 표시가 · 세금 포함 여부 미표기'}],address:'〒810-0041 福岡県福岡市中央区大名1-14-45 Qiz Tenjin 1F',lat:33.5876787,lng:130.3966611,mapQuery:'麺や兼虎 天神西通り店',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 4분',officialUrl:'https://www.kanetora.co.jp/shop#a05',menuUrl:'https://www.kanetora.co.jp/menu',image:'assets/restaurants/03-kanetora.webp',imageAlt:'멘야 카네토라 공식 메뉴의 농후 츠케멘',imageSource:'https://www.kanetora.co.jp/menu',evidenceNote:'지점·가격·사진: 카네토라 공식 사이트'},
  {number:4,id:'ichifuji-imaizumi',name:'もつ鍋 一藤 今泉本店',koreanName:'모츠나베 이치후지 이마이즈미 본점',category:'모츠나베',area:'이마이즈미',menus:[{name:'모츠나베 미소 (1인)',price:'1,958엔',priceNote:'세금 포함 · 2인분부터 · 차지 495엔'}],address:'〒810-0021 福岡県福岡市中央区今泉1-9-19 BuLaLaビル6F',lat:33.58590965,lng:130.39879073,mapQuery:'もつ鍋 一藤 今泉本店',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 8분',officialUrl:'https://www.ichifuji-f.jp/honten/',menuUrl:'https://www.ichifuji-f.jp/menu/',image:'assets/restaurants/04-ichifuji.webp',imageAlt:'이치후지 공식 메뉴의 미소 모츠나베',imageSource:'https://www.ichifuji-f.jp/menu/',evidenceNote:'지점·가격·조건·사진: 이치후지 공식 사이트'},
  {number:5,id:'rakutenti-tenjin-nishidori',name:'元祖もつ鍋 楽天地 天神西通り店',koreanName:'원조 모츠나베 라쿠텐치 텐진 니시도리점',category:'모츠나베',area:'다이묘',menus:[{name:'모츠나베 (1인)',price:'1,771엔',priceNote:'공식 메뉴 · 세금 포함'}],address:'〒810-0041 福岡県福岡市中央区大名2-1-58 1F',lat:33.58937884,lng:130.39411119,mapQuery:'元祖もつ鍋 楽天地 天神西通り店',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 3분',officialUrl:'https://rakutenti.com/shop/tenjindaimyou/',menuUrl:'https://rakutenti.com/menu/',image:'assets/restaurants/05-rakutenti.webp',imageAlt:'라쿠텐치 공식 메뉴의 부추 모츠나베',imageSource:'https://rakutenti.com/menu/',evidenceNote:'지점·가격·사진: 라쿠텐치 공식 사이트'},
  {number:6,id:'ooyama-fukuoka-parco',name:'博多もつ鍋 おおやま 福岡パルコ',koreanName:'하카타 모츠나베 오오야마 후쿠오카 파르코점',category:'모츠나베',area:'텐진',menus:[{name:'오오야마 세트 (1인)',price:'5,800엔',priceNote:'공식 지점 메뉴 · 세금 포함 · 2인부터'}],address:'〒810-0001 福岡県福岡市中央区天神2-11-2 福岡PARCO本館B1 増床エリア',lat:33.590779,lng:130.398641,mapQuery:'博多もつ鍋 おおやま 福岡パルコ',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 5분',officialUrl:'https://www.motu-ooyama.com/shop/tenjin/',menuUrl:'https://www.motu-ooyama.com/shop/tenjin/',image:'assets/restaurants/06-ooyama.webp',imageAlt:'오오야마 공식 메뉴의 모츠나베',imageSource:'https://www.motu-ooyama.com/shop/tenjin/',evidenceNote:'지점·세트 가격·16시 이후 좌석료 380엔: 오오야마 공식 파르코점 페이지'},
  {number:7,id:'mentaiju-nishinakasu',name:'元祖博多めんたい重（西中洲）',koreanName:'원조 하카타 멘타이쥬 니시나카스',category:'명란 요리',area:'니시나카스',menus:[{name:'멘타이쥬',price:'1,980엔',priceNote:'세금 포함'},{name:'멘타이쥬 상',price:'3,410엔',priceNote:'세금 포함'}],address:'〒810-0002 福岡県福岡市中央区西中洲6-15',lat:33.591197,lng:130.404076,mapQuery:'元祖博多めんたい重 西中洲',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 13분',officialUrl:'https://www.mentaiju.com/',menuUrl:'https://www.mentaiju.com/menu/',evidenceNote:'지점·가격: 멘타이쥬 공식 사이트',image:'assets/restaurants/07-mentaiju.webp',imageAlt:'원조 하카타 멘타이쥬의 명란 덮밥',imageSource:'https://www.mentaiju.com/menu/'},
  {number:8,id:'fukutaro-tenjin-terra',name:'FUKUTARO CAFE＆STORE 天神テルラ店',koreanName:'후쿠타로 카페 앤 스토어 텐진 테라점',category:'명란 요리',area:'텐진',menus:[{name:'갓 만든 명란 볼',price:'1,080엔',priceNote:'공식 시설 페이지 · 세금 포함'}],address:'〒810-0004 福岡県福岡市中央区渡辺通5-25-18 天神テルラ1F',lat:33.5892,lng:130.4014,mapQuery:'FUKUTARO CAFE STORE 天神テルラ店',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 9분',officialUrl:'https://www.tenjinterra.com/fukutaro.html',menuUrl:'https://www.tenjinterra.com/fukutaro.html',image:'assets/restaurants/08-fukutaro-tenjin-terra.webp',imageAlt:'후쿠타로 공식 시설 페이지의 갓 만든 명란 볼',imageSource:'https://www.tenjinterra.com/fukutaro.html',evidenceNote:'지점·가격·사진: 텐진 테라 공식 시설 페이지'},
  {number:9,id:'shinmiura-tenjin',name:'新三浦 天神店',koreanName:'신미우라 텐진점',category:'미즈타키',area:'텐진',menus:[{name:'미즈타키 소접시 정식',price:'2,850엔',priceNote:'공식 메뉴 표시가'},{name:'미즈타키 코스 하나',price:'4,700엔',priceNote:'공식 메뉴 표시가'}],address:'〒810-0001 福岡県福岡市中央区天神1-12-1 天神ビルB1F',lat:33.5915,lng:130.3981,mapQuery:'新三浦 天神店',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 7분',officialUrl:'https://shinmiura-tenjin.com/',menuUrl:'https://shinmiura-tenjin.com/',image:'assets/restaurants/09-shinmiura-tenjin.webp',imageAlt:'신미우라 공식 사이트의 미즈타키 소접시 정식',imageSource:'https://shinmiura-tenjin.com/',evidenceNote:'매장·가격·사진: 신미우라 텐진점 공식 사이트'},
  {number:10,id:'mamichan-yatai',name:'まみちゃん',koreanName:'마미짱 텐진 야타이',category:'포장마차',area:'텐진',menus:[{name:'야키라멘',price:'800엔',priceNote:'공개 페이지 2024-04-23 기재가 · 방문 전 확인'},{name:'차이니즈 나폴리',price:'800엔',priceNote:'공개 페이지 2024-04-23 기재가 · 방문 전 확인'}],address:'福岡県福岡市中央区天神2-13-1 일대',lat:33.5922,lng:130.3958,mapQuery:'屋台 まみちゃん 天神2-13-1',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 5분',officialUrl:'https://yatai-yokatai.com/yataidetails/?id=27',sourceUrl:'https://yatai-yokatai.com/yataidetails/?id=27',image:'assets/restaurants/10-mamichan-yatai.webp',imageAlt:'후쿠오카 야타이 정보 페이지의 마미짱 차이니즈 나폴리',imageSource:'https://yatai-yokatai.com/yataidetails/?id=27',evidenceNote:'위치·가격·사진: 후쿠오카 야타이 정보 사이트 · 최종갱신 2024-04-23'},
  {number:11,id:'pyonkichi',name:'屋台屋ぴょんきち',koreanName:'야타이야 뿅키치',category:'포장마차',area:'텐진',menus:[{name:'돼지삼겹 볶음',price:'1,100엔',priceNote:'2025-05 공식 관광 페이지 기준 · 세금 여부 미표기'},{name:'라멘',price:'750엔',priceNote:'2025-05 공식 관광 페이지 기준 · 세금 여부 미표기'},{name:'야키라멘',price:'900엔',priceNote:'2025-05 공식 관광 페이지 기준 · 세금 여부 미표기'}],address:'〒810-0001 福岡県福岡市中央区天神1-4-1',lat:33.588291,lng:130.401189,mapQuery:'屋台屋ぴょんきち 福岡',hotelAccess:'니시테츠 그랜드 호텔에서 도보 약 10분',officialUrl:'https://yokanavi.com/spots/122514',sourceUrl:'https://yokanavi.com/spots/122514',evidenceNote:'텐진의 屋台屋ぴょんきち · 후쿠오카시 관광정보 2025-05 게시 가격',image:'assets/restaurants/11-pyonkichi.webp',imageAlt:'야타이야 뿅키치의 돼지삼겹 볶음',imageSource:'https://yokanavi.com/spots/122514'}
];
