// 첨부 인포그래픽의 번호를 그대로 유지합니다. 가격 확인일: 2026-08-26.
export const restaurantGuide=[
  {number:1,id:'shinshin-tenjin',name:'博多純情らーめん ShinShin 天神本店',koreanName:'하카타 신신 라멘 텐진 본점',category:'라멘',area:'텐진',menus:[{name:'하카타 신신 라멘',price:'870엔',priceNote:'세금 포함'},{name:'반숙계란 라멘',price:'1,030엔',priceNote:'세금 포함'}],address:'〒810-0001 福岡県福岡市中央区天神3-2-19 1F',lat:33.592673,lng:130.396814,mapQuery:'博多純情らーめん ShinShin 天神本店',officialUrl:'https://www.hakata-shinshin.com/tenpo_tenjin',menuUrl:'https://www.hakata-shinshin.com/menu_tenjin01',image:'assets/restaurants/01-shinshin-tenjin.webp',imageAlt:'ShinShin 텐진 본점의 하카타 라멘',imageSource:'https://www.hakata-shinshin.com/tenpo_tenjin'},
  {number:2,id:'shinshin-deitos',name:'博多純情らーめん ShinShin 博多デイトス店',koreanName:'하카타 신신 라멘 하카타 데이토스점',category:'라멘',area:'하카타역',menus:[{name:'하카타 신신 라멘',price:'870엔',priceNote:'세금 포함'},{name:'반숙계란 라멘',price:'1,030엔',priceNote:'세금 포함'}],address:'〒812-0012 福岡県福岡市博多区博多駅中央街1-1 博多デイトス2F「博多めん街道」',lat:33.589384,lng:130.421019,mapQuery:'博多純情らーめん ShinShin 博多デイトス店',officialUrl:'https://www.hakata-shinshin.com/tenpo_deitos',menuUrl:'https://www.hakata-shinshin.com/menu_deitos01',image:'assets/restaurants/02-shinshin-deitos.webp',imageAlt:'ShinShin 하카타 데이토스점의 하카타 라멘',imageSource:'https://www.hakata-shinshin.com/tenpo_deitos'},
  {number:3,id:'kanetora-deitos',name:'麺や兼虎 博多デイトス店',koreanName:'멘야 카네토라 하카타 데이토스점',category:'츠케멘',area:'하카타역',menus:[{name:'농후 츠케멘',price:'1,300엔',priceNote:'공식 표시가 · 세금 포함 여부 미표기'},{name:'매운 츠케멘',price:'1,350엔',priceNote:'공식 표시가 · 세금 포함 여부 미표기'}],address:'〒812-0012 福岡県福岡市博多区博多駅中央街1-1 JR博多駅 博多めん街道内',lat:33.591003,lng:130.421258,mapQuery:'麺や兼虎 博多デイトス店',officialUrl:'https://www.kanetora.co.jp/shop#a02',menuUrl:'https://www.kanetora.co.jp/menu',image:'assets/restaurants/03-kanetora.webp',imageAlt:'멘야 카네토라의 진한 츠케멘',imageSource:'https://www.kanetora.co.jp/menu'},
  {number:4,id:'ichifuji-hakata',name:'もつ鍋 一藤 博多店',koreanName:'모츠나베 이치후지 하카타점',category:'모츠나베',area:'하카타역',menus:[{name:'모츠나베 후지 코스',price:'5,000엔',priceNote:'세금 포함 · 공식 메뉴 대표 코스'}],address:'〒812-0011 福岡県福岡市博多区博多駅前2-4-16',lat:33.590296,lng:130.416475,mapQuery:'もつ鍋 一藤 博多店',officialUrl:'https://www.ichifuji-f.jp/hakata/',menuUrl:'https://www.ichifuji-f.jp/menu/',image:'assets/restaurants/04-ichifuji.webp',imageAlt:'이치후지의 미소 모츠나베',imageSource:'https://www.ichifuji-f.jp/menu/'},
  {number:5,id:'rakutenti-hakata-ekimae',name:'博多もつ鍋 楽天地 博多駅前店',koreanName:'하카타 모츠나베 라쿠텐치 하카타역앞점',category:'모츠나베',area:'하카타역',menus:[{name:'모츠나베 (1인)',price:'1,771엔',priceNote:'세금 포함'},{name:'만족 코스',price:'3,399엔',priceNote:'세금 포함'}],address:'〒812-0011 福岡県福岡市博多区博多駅前3丁目20-5 寿ビル',lat:33.5888704479547,lng:130.41561855620733,mapQuery:'博多もつ鍋 楽天地 博多駅前店',officialUrl:'https://rakutenti.com/shop/hakata3/',menuUrl:'https://rakutenti.com/menu/',image:'assets/restaurants/05-rakutenti.webp',imageAlt:'라쿠텐치의 부추 모츠나베',imageSource:'https://rakutenti.com/menu/'},
  {number:6,id:'ooyama-honten',name:'博多もつ鍋 おおやま本店',koreanName:'하카타 모츠나베 오오야마 본점',category:'모츠나베',area:'고후쿠마치',menus:[{name:'미소·쇼유 모츠나베 (1인)',price:'2,178엔',priceNote:'세금 포함 · 별도 좌석료 400엔'}],address:'〒812-0025 福岡県福岡市博多区店屋町7-28',lat:33.5966768416461,lng:130.40713687678635,mapQuery:'博多もつ鍋 おおやま本店',officialUrl:'https://www.motu-ooyama.com/shop/honten/',menuUrl:'https://www.motu-ooyama.com/shop/honten/',image:'assets/restaurants/06-ooyama.webp',imageAlt:'오오야마 본점의 모츠나베',imageSource:'https://www.motu-ooyama.com/shop/honten/'},
  {number:7,id:'mentaiju-nishinakasu',name:'元祖博多めんたい重（西中洲）',koreanName:'원조 하카타 멘타이쥬 니시나카스',category:'명란 요리',area:'니시나카스',menus:[{name:'멘타이쥬',price:'1,980엔',priceNote:'세금 포함'},{name:'멘타이쥬 상',price:'3,410엔',priceNote:'세금 포함'}],address:'〒810-0002 福岡県福岡市中央区西中洲6-15',lat:33.591197,lng:130.404076,mapQuery:'元祖博多めんたい重 西中洲',officialUrl:'https://www.mentaiju.com/',menuUrl:'https://www.mentaiju.com/menu/',image:'assets/restaurants/07-mentaiju.webp',imageAlt:'원조 하카타 멘타이쥬의 명란 덮밥',imageSource:'https://www.mentaiju.com/menu/'},
  {number:8,id:'shoboan',name:'めんたい料理 博多 椒房庵',koreanName:'멘타이 요리 하카타 쇼보안',category:'명란 요리',area:'하카타역',menus:[{name:'멘타이 도미 마부시',price:'3,300엔',priceNote:'세금 포함'}],address:'〒812-0012 福岡県福岡市博多区博多駅中央街1-1 JR博多シティ9F シティダイニング「くうてん」内',lat:33.590247780734195,lng:130.4183587657375,mapQuery:'めんたい料理 博多 椒房庵',officialUrl:'https://www.kayanoya.com/shop/gohanya-syoubouan/',menuUrl:'https://www.kayanoya.com/news/archives/1112',image:'assets/restaurants/08-shoboan.webp',imageAlt:'쇼보안의 멘타이 도미 마부시',imageSource:'https://www.kayanoya.com/news/archives/1112'},
  {number:9,id:'hamadaya-kooten',name:'博多水たき 濱田屋 くうてん',koreanName:'하카타 미즈타키 하마다야 쿠텐',category:'미즈타키',area:'하카타역',menus:[{name:'미즈타키 세트',price:'3,600엔',priceNote:'세금 포함 · 방문 직전 공식 메뉴 재확인'},{name:'미즈타키 코스',price:'4,800엔',priceNote:'세금 포함 · 방문 직전 공식 메뉴 재확인'}],address:'〒812-0012 福岡県福岡市博多区博多駅中央街1-1 アミュプラザ博多10階',lat:33.5906708,lng:130.4197755,mapQuery:'博多水たき 濱田屋 くうてん',officialUrl:'https://mizutaki-hamadaya.jp/kooten/',menuUrl:'https://mizutaki-hamadaya.jp/kooten/',image:'assets/restaurants/09-hamadaya.webp',imageAlt:'하마다야 쿠텐의 하카타 미즈타키',imageSource:'https://mizutaki-hamadaya.jp/kooten/'},
  {number:10,id:'nakasu-yatai',name:'中洲屋台街',koreanName:'나카스 포장마차 거리',category:'포장마차 구역',area:'나카스',menus:[{name:'돈코츠·야키라멘 등',price:'약 900~1,100엔대',priceNote:'공식 관광 등록 점포 사례(2023-12) 참고 · 특정 점포 가격 아님 · 현장 메뉴판 재확인'}],address:'福岡市博多区中洲1丁目 清流公園・那珂川沿い',lat:33.5903962,lng:130.4083,mapQuery:'中洲屋台街 清流公園',officialUrl:'https://yokanavi.com/yatai',sourceUrl:'https://yokanavi.com/spots/161395',image:'assets/restaurants/10-nakasu-yatai.webp',imageAlt:'나카스 강변의 포장마차 거리',imageSource:'https://yokanavi.com/spots/161395'},
  {number:11,id:'pyonkichi',name:'屋台屋ぴょんきち',koreanName:'야타이야 뿅키치',category:'포장마차',area:'텐진',menus:[{name:'돼지삼겹 볶음',price:'1,100엔',priceNote:'2025-05 공식 관광 페이지 기준 · 세금 여부 미표기'},{name:'라멘',price:'750엔',priceNote:'2025-05 공식 관광 페이지 기준 · 세금 여부 미표기'},{name:'야키라멘',price:'900엔',priceNote:'2025-05 공식 관광 페이지 기준 · 세금 여부 미표기'}],address:'〒810-0001 福岡県福岡市中央区天神1-4-1',lat:33.588291,lng:130.401189,mapQuery:'屋台屋ぴょんきち 福岡',officialUrl:'https://yokanavi.com/spots/122514',sourceUrl:'https://yokanavi.com/spots/122514',image:'assets/restaurants/11-pyonkichi.webp',imageAlt:'야타이야 뿅키치의 돼지삼겹 볶음',imageSource:'https://yokanavi.com/spots/122514'}
];
